/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/App/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/App/AppHeader.vue')['default']
    ButtonPrimary: typeof import('./src/components/Hopp/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./src/components/Hopp/ButtonSecondary.vue')['default']
    Codegen: typeof import('./src/components/RestRightSideBar/Codegen.vue')['default']
    Collections: typeof import('./src/components/RestRightSideBar/Collections.vue')['default']
    DocumentGen: typeof import('./src/components/RestRightSideBar/DocumentGen.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    HTMLLensRenderer: typeof import('./src/components/Lenses/HTMLLensRenderer.vue')['default']
    HttpBody: typeof import('./src/components/Rest/HttpBody.vue')['default']
    HttpHeaders: typeof import('./src/components/Rest/HttpHeaders.vue')['default']
    HttpMethodAndUrl: typeof import('./src/components/Rest/HttpMethodAndUrl.vue')['default']
    HttpParams: typeof import('./src/components/Rest/HttpParams.vue')['default']
    HttpRawBody: typeof import('./src/components/Rest/HttpRawBody.vue')['default']
    HttpReponse: typeof import('./src/components/Rest/HttpReponse.vue')['default']
    Input: typeof import('./src/components/Hopp/Input.vue')['default']
    Item: typeof import('./src/components/Hopp/Item.vue')['default']
    JSONLensRenderer: typeof import('./src/components/Lenses/JSONLensRenderer.vue')['default']
    KeyValue: typeof import('./src/components/Rest/KeyValue.vue')['default']
    Link: typeof import('./src/components/Hopp/Link.vue')['default']
    Placeholder: typeof import('./src/components/Hopp/Placeholder.vue')['default']
    RawLensRenderer: typeof import('./src/components/Lenses/RawLensRenderer.vue')['default']
    RequestOptions: typeof import('./src/components/Rest/RequestOptions.vue')['default']
    RequestTab: typeof import('./src/components/Rest/RequestTab.vue')['default']
    ResponseBody: typeof import('./src/components/Rest/ResponseBody.vue')['default']
    ResponseHeaders: typeof import('./src/components/Rest/ResponseHeaders.vue')['default']
    ResponseHeadersEntry: typeof import('./src/components/Rest/ResponseHeadersEntry.vue')['default']
    RestMain: typeof import('./src/components/Rest/RestMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectWrapper: typeof import('./src/components/Hopp/SelectWrapper.vue')['default']
    ShortCutPrompt: typeof import('./src/components/Rest/ShortCutPrompt.vue')['default']
    SidebarIndex: typeof import('./src/components/RestRightSideBar/SidebarIndex.vue')['default']
    SideMenu: typeof import('./src/components/App/SideMenu.vue')['default']
    Spinner: typeof import('./src/components/Hopp/Spinner.vue')['default']
    Tab: typeof import('./src/components/Hopp/Tab.vue')['default']
    TabHead: typeof import('./src/components/Rest/TabHead.vue')['default']
    Tabs: typeof import('./src/components/Hopp/Tabs.vue')['default']
    Window: typeof import('./src/components/Hopp/Window.vue')['default']
    Windows: typeof import('./src/components/Hopp/Windows.vue')['default']
    XMLLensRenderer: typeof import('./src/components/Lenses/XMLLensRenderer.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
